on:
  push:
    branches:
      - main
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - run: ls
      - run: mkdir .env
      - run: echo "${{ secrets.DOTENV }}" >> ./.env
      - run: cat ./.env
      - run: ls

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_USER_ID }}
          aws-secret-access-key: ${{ secrets.AWS_USER_PW }}
          aws-region: ap-northeast-2
      - name: SSH Commands
        uses: appleboy/ssh-action@v0.1.6
        with:
          host: ${{ secrets.AWS_SSH_HOST }}
          username: ${{ secrets.AWS_SSH_USERNAME }}
          key: ${{ secrets.AWS_SSH_KEY }}
          port: ${{ secrets.AWS_SSH_PORT }}
          script: |
            cd front-ilogu
            git reset --hard origin/main
            git pull
            npm install
            npm run build
            sudo systemctl stop nginx.service
            sudo systemctl start nginx.service
